# TP6

### `Resolver usando Pandas`

Resolver los ejercicios del TP3 utilizando la librer√≠a Pandas.

### Ejercicio 1: Cargar Datos de ventas.

El archivo datos.dat contiene el registro de las ventas realizadas.

Tiene un formato de ancho fijo:
- `fecha`:    10 lugares
- `producto`: 30 lugares
- `precio`:   10 lugares
- `cantidad`:  5 lugares

Hacer una funcion que cargue los datos en un DataFrame de Pandas.

In [28]:
import pandas as pd 
    
def cargar_datos():
    with open("datos.dat", "r") as file:
        lineas = file.readlines()
    
    lista = {
        "fecha": [],
        "nombre": [],
        "precio": [],
        "cantidad": []
    }
    
    for a in lineas:
        a = a.strip()
        if not a:
            continue
        fecha = a[0:10].strip()  
        nombre = a[10:40].strip()
        precio = a[40:50].strip()
        cantidad = a[50:55].strip()
        
        lista["fecha"].append(fecha)
        lista["nombre"].append(nombre)
        lista["precio"].append(float(precio))
        lista["cantidad"].append(int(cantidad))

    return pd.DataFrame(lista)

datos = cargar_datos()
datos

         fecha      nombre  precio  cantidad
0   2024-08-27     Mirinda  1510.0        14
1   2024-08-27     Mirinda  1560.0        12
2   2024-08-28     Torasso   940.0         8
3   2024-08-29  Pepsi Cola  1210.0        10
4   2024-08-30     Mirinda  1520.0         1
5   2024-09-01     Mirinda  1550.0        15
6   2024-09-01      Sprite   810.0         4
7   2024-09-02   Coca Cola  1100.0         4
8   2024-09-02  Pepsi Cola  1220.0        13
9   2024-09-02     Torasso   910.0         5
10  2024-09-02     Torasso   920.0         3
11  2024-09-03   Coca Cola  1020.0         8
12  2024-09-03     Mirinda  1570.0         7
13  2024-09-03     Mirinda  1590.0         2
14  2024-09-04  Pepsi Cola  1220.0        13
15  2024-09-05     Mirinda  1500.0         3
16  2024-09-05  Pepsi Cola  1300.0         5
17  2024-09-06   Coca Cola  1080.0         1
18  2024-09-06      Sprite   860.0        12
19  2024-09-06     Torasso   930.0         3
20  2024-09-07   Coca Cola  1080.0        14
21  2024-09-07      Sprite   870.0        13
22  2024-09-08   Coca Cola  1040.0        10
23  2024-09-08     Mirinda  1580.0         2
24  2024-09-08  Pepsi Cola  1240.0         9
25  2024-09-09     Mirinda  1500.0         3
26  2024-09-09      Sprite   850.0         9
27  2024-09-10     Mirinda  1590.0         8
28  2024-09-10  Pepsi Cola  1250.0        12
29  2024-09-11      Sprite   810.0         6
30  2024-09-11      Sprite   820.0        14
31  2024-09-12   Coca Cola  1080.0         4
32  2024-09-13     Mirinda  1580.0         5
33  2024-09-13  Pepsi Cola  1250.0        13
34  2024-09-14   Coca Cola  1080.0        15
35  2024-09-14  Pepsi Cola  1270.0        14
36  2024-09-15   Coca Cola  1100.0         1
37  2024-09-15     Mirinda  1500.0        13
38  2024-09-15      Sprite   870.0        14
39  2024-09-15     Torasso   900.0        13

### Ejercicio 2: Calcular el total de ventas.
Hacer una funci√≥n que sume los importes vendidos (precio * cantidad) y las cantidades.

In [41]:

def calcular_totales(datos):
    ventas = datos.precio * datos.cantidad
    ventas_total = ventas.sum()
    unidades = datos.cantidad.sum()
    return ventas_total, unidades
    
importe, cantidad = calcular_totales(datos)
print(f"Las ventas fueron de ${importe:.2f} en {cantidad} unidades")

Las ventas fueron de $392730.00 en 335 unidades

### Ejercicio 3: Listar las unidades vendidas.
Listar cu√°ntas unidades se vendieron en total para cada producto

In [52]:
def unidades_vendidas(datos):
    unidades = datos.groupby("nombre").cantidad.sum()
    print(unidades)
    
        
unidades_vendidas(datos)

nombre
Coca Cola     57
Mirinda       85
Pepsi Cola    89
Sprite        72
Torasso       32
Name: cantidad, dtype: int64

###  Ejercicio 4: Listar el precio promedio por producto.
Hacer un listado del precio promedio por producto.

In [56]:
def precio_promedio(datos):
    precio_prom = datos.groupby("nombre").precio.mean()
    print(precio_prom)
    
precio_promedio(datos)

nombre
Coca Cola     1072.500000
Mirinda       1545.833333
Pepsi Cola    1245.000000
Sprite         841.428571
Torasso        920.000000
Name: precio, dtype: float64

### Ejercicio 5: Ranking de productos
Realizar un listado de los 3 productos m√°s vendidos ordenados por la cantidad de unidades vendidas (ordenadas de mayor a menor)

In [68]:
def ranking_productos(datos, top=3):
    ranking = datos.groupby("nombre").cantidad.sum().sort_values(ascending=False)
    print(f"Ranking de los productos mas vendidos: {ranking.head(top)}")
    

ranking_productos(datos)

Ranking de los productos mas vendidos: nombre
Torasso      32
Coca Cola    57
Sprite       72
Name: cantidad, dtype: int64

### Ejercicio 6: Listar las ventas por mes
Realizar un listado del total de unidades vendidas por producto separado por mes.

In [69]:
def ventas_por_mes(datos):
    datos["fecha"] = pd.to_datetime(datos["fecha"])
    datos["mes"] = datos["fecha"].dt.month
    ventas = datos.groupby("mes").cantidad.sum()
    print(ventas)

ventas_por_mes(datos)

mes
8     45
9    290
Name: cantidad, dtype: int64

### Ejercicio 7: Informe general

Mostrar un listado de productos ordenados alfabeticamente que contengan el precio promedio, la cantidad de unidades vendidas y el importe total vendido para cada producto

In [77]:
def resumen_ventas(datos):
    resumen = datos.groupby("nombre").agg({"precio": "mean", "cantidad": "sum"})
    resumen["total"] = resumen.precio * resumen.cantidad
    print(resumen)

resumen_ventas(datos)

                 precio  cantidad          total
nombre
Coca Cola   1072.500000        57   61132.500000
Mirinda     1545.833333        85  131395.833333
Pepsi Cola  1245.000000        89  110805.000000
Sprite       841.428571        72   60582.857143
Torasso      920.000000        32   29440.000000

## `Resolver usando NumPy`
## Resolver el ejercicio 2 del tp1 usando NumPy

### Ejercicio 8

Escribe una funci√≥n en Python que encuentre los valores de `a`, `b`, y `c` para que la funci√≥n cuadr√°tica `f(x) = a x^2 + b x + c` pase exactamente por los siguientes puntos:

| x  | y  |
|---:|---:|
|  0 |  0 |
|  1 |  8 |
|  2 | 12 |
|  3 | 12 |
|  5 |  0 |

### Requisitos:
- La funci√≥n debe explorar posibles valores de `a`, `b`, y `c` utilizando un m√©todo de prueba y error.
- Debe devolver los valores que hagan que la diferencia entre la funci√≥n `f(x)` y los valores medidos `y` sea exactamente cero para cada punto.

> **Pista**: Los valores de `a`, `b`, y `c` son n√∫meros peque√±os.

La idea es implementar el mismo algoritmo que se uso en el TP1 pero usando NumPy en lugar de Python puro.

In [86]:
import numpy as np

def f(x, coeficientes):
    a,b,c = coeficientes
    return a*x**2 + b*x + c

def error(y, y_pred):
    return y - y_pred

X = np.array([0,1,2,3,5])
Y = np.array([0,8,12,12,0])

def buscar_coeficientes():
   coeficientes = np.polyfit(X, Y, 2)
   return coeficientes

coeficientes = buscar_coeficientes()
coeficientes

array([-2.00000000e+00,  1.00000000e+01, -1.27105749e-14])

### Ejercicio 9: Resolver el ejercicio 3 del TP1 usando NumPy
Buscar los coeficientes de la funci√≥n que minimice la suma de los cuadrados de las diferencias entre los valores medidos y los valores de la funci√≥n.

1. Crear un array con los coeficientes elegidos al azar (usar `randint(-10,10,3)`).
2. Calcular el valor de la funci√≥n y el error correspondiente.
3. Mientras que el error sea mayor a 1:
    1. Definir nuevos coeficientes agreg√°ndoles un peque√±o valor al azar a los coeficientes actuales (aprendizaje = 0.001).
    2. Si el error para los nuevos coeficientes es menor que el anterior, reemplazar los coeficientes actuales por los nuevos.

In [93]:
import numpy as np
from numpy.random import randint

def f(x, coeficientes):
    a, b, c = coeficientes
    return a * x**2 + b * x + c

def error(y, y_pred):
    return np.sum((y - y_pred)**2)

X = np.array([0, 1, 2, 3, 5])

def buscar_coeficientes():
    coeficientes = randint(-10, 10, 3)
    e = error(Y, f(X, coeficientes))
    max_iteraciones = 10000  
    iteraciones = 0
    
    while e > 1 and iteraciones < max_iteraciones:
        nuevos_coeficientes = coeficientes + randint(-1, 2, 3) SSSSSSSSSSS"
        nuevo_error = error(Y, f(X, nuevos_coeficientes))
        
        if nuevo_error < e:
            coeficientes = nuevos_coeficientes
            e = nuevo_error
        
        iteraciones += 1
    
    return coeficientes

coeficientes = buscar_coeficientes()
print(coeficientes)

[0 0 6]