# TP6

### `Resolver usando Pandas`

Resolver los ejercicios del TP3 utilizando la librer√≠a Pandas.

### Ejercicio 1: Cargar Datos de ventas.

El archivo datos.dat contiene el registro de las ventas realizadas.

Tiene un formato de ancho fijo:
- `fecha`:    10 lugares
- `producto`: 30 lugares
- `precio`:   10 lugares
- `cantidad`:  5 lugares

Hacer una funcion que cargue los datos en un DataFrame de Pandas.

In [56]:
import pandas as pd
def cargar_datos():
    datos = open("datos.dat", "r").readlines()
    prueba = []

    for dato in datos:
        fecha = dato[0:10].strip()
        producto = dato[10:40].strip()
        precio = float(dato[40:50].strip())
        cantidad = int(dato[50:55].strip())
    
        diccionario = {"Producto": producto, "Precio": precio, "Cantidad": cantidad, "Fecha": fecha}

        prueba.append(diccionario)

    df = pd.DataFrame(prueba)
        
    return df
datos = cargar_datos()
datos

      Producto  Precio  Cantidad       Fecha
0      Mirinda  1510.0        14  2024-08-27
1      Mirinda  1560.0        12  2024-08-27
2      Torasso   940.0         8  2024-08-28
3   Pepsi Cola  1210.0        10  2024-08-29
4      Mirinda  1520.0         1  2024-08-30
5      Mirinda  1550.0        15  2024-09-01
6       Sprite   810.0         4  2024-09-01
7    Coca Cola  1100.0         4  2024-09-02
8   Pepsi Cola  1220.0        13  2024-09-02
9      Torasso   910.0         5  2024-09-02
10     Torasso   920.0         3  2024-09-02
11   Coca Cola  1020.0         8  2024-09-03
12     Mirinda  1570.0         7  2024-09-03
13     Mirinda  1590.0         2  2024-09-03
14  Pepsi Cola  1220.0        13  2024-09-04
15     Mirinda  1500.0         3  2024-09-05
16  Pepsi Cola  1300.0         5  2024-09-05
17   Coca Cola  1080.0         1  2024-09-06
18      Sprite   860.0        12  2024-09-06
19     Torasso   930.0         3  2024-09-06
20   Coca Cola  1080.0        14  2024-09-07
21      Sprite   870.0        13  2024-09-07
22   Coca Cola  1040.0        10  2024-09-08
23     Mirinda  1580.0         2  2024-09-08
24  Pepsi Cola  1240.0         9  2024-09-08
25     Mirinda  1500.0         3  2024-09-09
26      Sprite   850.0         9  2024-09-09
27     Mirinda  1590.0         8  2024-09-10
28  Pepsi Cola  1250.0        12  2024-09-10
29      Sprite   810.0         6  2024-09-11
30      Sprite   820.0        14  2024-09-11
31   Coca Cola  1080.0         4  2024-09-12
32     Mirinda  1580.0         5  2024-09-13
33  Pepsi Cola  1250.0        13  2024-09-13
34   Coca Cola  1080.0        15  2024-09-14
35  Pepsi Cola  1270.0        14  2024-09-14
36   Coca Cola  1100.0         1  2024-09-15
37     Mirinda  1500.0        13  2024-09-15
38      Sprite   870.0        14  2024-09-15
39     Torasso   900.0        13  2024-09-15

### Ejercicio 2: Calcular el total de ventas.
Hacer una funci√≥n que sume los importes vendidos (precio * cantidad) y las cantidades.

In [57]:
def calcular_totales(datos):
    importe = sum(datos["Precio"] * datos["Cantidad"])
    cantidad = sum(datos["Cantidad"])
    
    return importe, cantidad 
importe, cantidad = calcular_totales(datos)

print(f"Las ventas fueron de ${importe:.2f} en {cantidad} unidades")

Las ventas fueron de $392730.00 en 335 unidades

### Ejercicio 3: Listar las unidades vendidas.
Listar cu√°ntas unidades se vendieron en total para cada producto

In [58]:
def unidades_vendidas(datos):
    print("Unidades vendidas por producto:")
    productos = datos.groupby("Producto")
    resultado = productos["Cantidad"].sum()

    resultado = resultado.apply(lambda x: f"{x}u")
    
    return resultado

unidades_vendidas(datos)

Unidades vendidas por producto:

Producto
Coca Cola     57u
Mirinda       85u
Pepsi Cola    89u
Sprite        72u
Torasso       32u
Name: Cantidad, dtype: object

###  Ejercicio 4: Listar el precio promedio por producto.
Hacer un listado del precio promedio por producto.

In [59]:
def precio_promedio(datos):
    print("Precio promedio por producto:")
    productos = datos.groupby("Producto")
    precio_prom = productos["Precio"].mean()

    pd.options.display.float_format = '${:,.2f}'.format

    return precio_prom
precio_promedio(datos)

Precio promedio por producto:

Producto
Coca Cola    $1,072.50
Mirinda      $1,545.83
Pepsi Cola   $1,245.00
Sprite         $841.43
Torasso        $920.00
Name: Precio, dtype: float64

### Ejercicio 5: Ranking de productos
Realizar un listado de los 3 productos m√°s vendidos ordenados por la cantidad de unidades vendidas (ordenadas de mayor a menor)

In [60]:
def ranking_productos(datos, top=3):
    print(f"Top {top} productos m√°s vendidos:")
    productos = datos.groupby("Producto")
    resultado = productos["Cantidad"].sum().sort_values(ascending = False).head(top)

    resultado = resultado.apply(lambda x: f"{x}u")

    return resultado

ranking_productos(datos)

Top 3 productos m√°s vendidos:

Producto
Pepsi Cola    89u
Mirinda       85u
Sprite        72u
Name: Cantidad, dtype: object

### Ejercicio 6: Listar las ventas por mes
Realizar un listado del total de unidades vendidas por producto separado por mes.

In [61]:
import locale
def ventas_por_mes(datos):
    locale.setlocale(locale.LC_TIME, "Spanish_Spain.1252")
    datos["Fecha"] = pd.to_datetime(datos["Fecha"])
    datos["Mes"] = datos["Fecha"].dt.strftime("%B")

    ventas = datos.groupby(["Producto", "Mes"])["Cantidad"].sum().reset_index()
    ventas = ventas.sort_values(by=["Mes", "Producto"])

    mes_actual = None
    
    for indx,row in ventas.iterrows():
        if row["Mes"] != mes_actual:
            mes_actual = row["Mes"]
            print(f"\nVentas en {mes_actual.capitalize()}:\n" + "-" * 30)
        print(f"{row['Producto']:12} {row['Cantidad']:5} unidades")

    return

ventas_por_mes(datos)

Ventas en Agosto:
------------------------------
Mirinda         27 unidades
Pepsi Cola      10 unidades
Torasso          8 unidades

Ventas en Septiembre:
------------------------------
Coca Cola       57 unidades
Mirinda         58 unidades
Pepsi Cola      79 unidades
Sprite          72 unidades
Torasso         24 unidades

### Ejercicio 7: Informe general

Mostrar un listado de productos ordenados alfabeticamente que contengan el precio promedio, la cantidad de unidades vendidas y el importe total vendido para cada producto

In [62]:
def resumen_ventas(datos):
    datos["Importe Total"] = datos["Precio"] * datos["Cantidad"]
    listado = datos.groupby("Producto").agg({"Importe Total": "sum", "Cantidad": "sum", "Precio": "mean"})

    listado = listado.rename(columns={"Cantidad": "Unidades Vendidas", "Precio": "Precio Promedio"})

    return listado
    
resumen_ventas(datos)

            Importe Total  Unidades Vendidas  Precio Promedio
Producto
Coca Cola      $60,780.00                 57        $1,072.50
Mirinda       $131,080.00                 85        $1,545.83
Pepsi Cola    $110,510.00                 89        $1,245.00
Sprite         $61,040.00                 72          $841.43
Torasso        $29,320.00                 32          $920.00

## `Resolver usando NumPy`
## Resolver el ejercicio 2 del tp1 usando NumPy

### Ejercicio 8

Escribe una funci√≥n en Python que encuentre los valores de `a`, `b`, y `c` para que la funci√≥n cuadr√°tica `f(x) = a x^2 + b x + c` pase exactamente por los siguientes puntos:

| x  | y  |
|---:|---:|
|  0 |  0 |
|  1 |  8 |
|  2 | 12 |
|  3 | 12 |
|  5 |  0 |

### Requisitos:
- La funci√≥n debe explorar posibles valores de `a`, `b`, y `c` utilizando un m√©todo de prueba y error.
- Debe devolver los valores que hagan que la diferencia entre la funci√≥n `f(x)` y los valores medidos `y` sea exactamente cero para cada punto.

> **Pista**: Los valores de `a`, `b`, y `c` son n√∫meros peque√±os.

La idea es implementar el mismo algoritmo que se uso en el TP1 pero usando NumPy en lugar de Python puro.

In [63]:
import numpy as np
def f(x, coeficientes):
    a,b,c = coeficientes
    return a*x**2 + b*x + c

def error(y, y_pred):
    return y - y_pred

X = np.array([0,1,2,3,5])
Y = np.array([0,8,12,12,0])

def buscar_coeficientes():
    coeficientes = np.polyfit(X,Y,2)
    y_pred = f(X, coeficientes)
    err = error(Y, y_pred)

    if np.allclose(err, 0):
        return f"Los coeficientes encontrados son: {np.rint(coeficientes).astype(int)}"

coeficientes = buscar_coeficientes()
coeficientes

'Los coeficientes encontrados son: [-2 10  0]'

### Ejercicio 9: Resolver el ejercicio 3 del TP1 usando NumPy
Buscar los coeficientes de la funci√≥n que minimice la suma de los cuadrados de las diferencias entre los valores medidos y los valores de la funci√≥n.

1. Crear un array con los coeficientes elegidos al azar (usar `randint(-10,10,3)`).
2. Calcular el valor de la funci√≥n y el error correspondiente.
3. Mientras que el error sea mayor a 1:
    1. Definir nuevos coeficientes agreg√°ndoles un peque√±o valor al azar a los coeficientes actuales (aprendizaje = 0.001).
    2. Si el error para los nuevos coeficientes es menor que el anterior, reemplazar los coeficientes actuales por los nuevos.

In [64]:
import numpy as np
from numpy.random import randint

def f(x, coeficientes):
    a,b,c = coeficientes
    return a*x**2 + b*x + c

def error(y, y_pred):
    return np.sum((y - y_pred)**2)

X = np.array([0, 1, 2, 3, 5])
Y = np.array([0, 8,12,11, 1]) # Observar que no son los mismos valores que en el ejemplo anterior

def buscar_coeficientes():
    coeficientes = randint(-10, 10, 3)
    y_p = f(X, coeficientes)
    e = error(Y, y_p)
    aprendizaje = 0.00001

    while e > 1:
        nuevos_coeficientes = coeficientes + randint(-10, 10, 3) * aprendizaje
        y_p2 = f(X, nuevos_coeficientes)
        e2 = error(Y, y_p2)

        if e2 < e:
            coeficientes = nuevos_coeficientes
            e = e2
    return f"Los coeficientes son: {coeficientes} y el error es: {e}"
coeficientes = buscar_coeficientes()
coeficientes

'Los coeficientes son: [-1.77877  8.9562   0.62052] y el error es: 0.9999493275008361'